name = "konty-website"
main = ".output/server/index.mjs"
compatibility_date = "2024-09-01"
workers_dev = false

# Enable Node.js compatibility for Nuxt/Nitro
compatibility_flags = ["nodejs_compat"]

# Smart Placement - Automatically runs worker in optimal location
[placement]
mode = "smart"

# Observability - Enable logging and analytics
[observability]
enabled = true

# Performance limits
[limits]
cpu_ms = 50

# Build configuration (if using wrangler for builds)
[build]
command = "pnpm build"
cwd = "."
watch_paths = ["./app", "./server", "./config", "./nuxt.config.ts"]

# Upload configuration
[build.upload]
format = "service-worker"

# Production environment variables
[vars]
NODE_ENV = "production"
APP_ENV = "production"
#NUXT_PUBLIC_SITE_URL = "https://konty.com"
NUXT_PUBLIC_SITE_URL = "https://konty-website.codeusteam.workers.dev"
GTM_ID = "GTM-MM5BP25F"
NUXT_UI_PRO_LICENSE = "24880184-C60C-472E-82F7-CBFE4D0A9ABA"

# Production routes (add your domain after configuring in Cloudflare)
# Uncomment when ready to use custom domain
# [[routes]]
# pattern = "konty.com"
# zone_name = "konty.com"
#
# [[routes]]
# pattern = "www.konty.com"
# zone_name = "konty.com"

# Staging environment
[env.staging]
name = "staging-konty-website"
workers_dev = true

# Staging environment variables
[env.staging.vars]
NODE_ENV = "production"
APP_ENV = "staging"
NUXT_PUBLIC_SITE_URL = "https://staging-konty-website.codeusteam.workers.dev"
GTM_ID = "GTM-5PP3XMG7"
NUXT_UI_PRO_LICENSE = "24880184-C60C-472E-82F7-CBFE4D0A9ABA"

# Staging also uses Smart Placement
[env.staging.placement]
mode = "smart"

# Development environment (local testing)
[env.development]
name = "dev-konty-website"
workers_dev = true

[env.development.vars]
NODE_ENV = "development"
APP_ENV = "development"
NUXT_PUBLIC_SITE_URL = "http://localhost:8787"
GTM_ID = "GTM-5PP3XMG7"
NUXT_UI_PRO_LICENSE = "24880184-C60C-472E-82F7-CBFE4D0A9ABA"
