import type { LocaleConfig } from "~/types/locale"
import { DEFAULT_LOCALE, VALID_LOCALES } from "../../config/locale.config"

interface SeoMetaOptions {
  title: string
  description: string
  image?: string            // Optional explicit OG image
  type?: 'website' | 'article' | 'book' | 'profile'
  url?: string              // Optional canonical override
  robots?: string           // Optional robots override per page
  noindex?: boolean         // Convenience flag to noindex a page
}

/**
 * Get all locale variants of the current URL
 * Useful for generating alternate links in structured data
 */
export function getAllLocaleUrls(path: string, siteUrl?: string): Record<string, string> {
  const baseUrl = siteUrl || 'https://konty.com'
  const urls: Record<string, string> = {}
  
  // Remove any existing locale prefix
  const cleanPath = path.replace(/^\/(me|ba|us)/, '') || '/'
  
  VALID_LOCALES.forEach(locale => {
    const localePath = locale === DEFAULT_LOCALE 
      ? cleanPath 
      : `/${locale}${cleanPath}`
    urls[locale] = `${baseUrl}${localePath}`
  })
  
  return urls
}

// Note: hreflang tags are automatically generated by @nuxtjs/i18n module
// We removed manual generation to prevent duplicates in HTML output
// The i18n module handles this based on the locales configuration in nuxt.config.ts

/**
 * Centralized SEO for all pages:
 * - SSR-safe canonical from runtimeConfig.public.siteUrl + route
 * - OG/Twitter images: either explicit or a default
 * - i18n-aware: sets og:locale and hreflang tags
 * - Proper canonical URLs per locale
 */
export const useCustomSeoMeta = (options: SeoMetaOptions) => {
  const route = useRoute()
  const { locale, locales } = useI18n()
  const config = useRuntimeConfig()

  // Get site URL from config
  const siteUrl = config.public.siteUrl || 'https://konty.com'

  // Build proper canonical URL with locale handling
  const pathWithoutLocale = route.path.replace(/^\/(me|ba|us)/, '') || '/'
  const canonicalPath = locale.value === DEFAULT_LOCALE
    ? pathWithoutLocale
    : `/${locale.value}${pathWithoutLocale}`
  const canonical = options.url || `${siteUrl}${canonicalPath}`

  // Get OG image configuration for current route
  const { getOgImageConfig } = await import('~/config/og-images')
  const ogImageConfig = getOgImageConfig(route.path)
  
  // Build absolute URL for OG image (required by social platforms)
  const seoImage = options.image || `${siteUrl}${ogImageConfig.path}`

  // Map i18n locale to OpenGraph locale
  const ogLocale = computed(() => {
    const current = (locales.value as LocaleConfig[]).find(l => l.code === locale.value)
    return current?.iso || 'sr-RS'
  })

  useSeoMeta({
    // Basic
    title: options.title,
    description: options.description,

    // Canonical
    ogUrl: canonical,

    // OpenGraph
    ogTitle: options.title,
    ogDescription: options.description,
    ogImage: seoImage,
    ogType: options.type || 'website',
    ogSiteName: 'Konty',
    ogLocale: ogLocale.value,

    // Twitter
    twitterCard: 'summary_large_image',
    twitterTitle: options.title,
    twitterDescription: options.description,
    twitterImage: seoImage,

    // Robots (page-specific override or noindex flag)
    robots: options.noindex ? 'noindex, nofollow' : (options.robots || 'index, follow'),
    author: 'Konty Team'
  })

  // Add canonical link only - hreflang is handled by @nuxtjs/i18n module
  // This prevents duplicate hreflang tags in the HTML output
  useHead({
    link: [
      { rel: 'canonical', href: canonical }
    ],
    htmlAttrs: {
      lang: ogLocale.value
    }
  })
}
