name: Deploy to Staging

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    name: Deploy to Cloudflare Workers - Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Build for staging
        run: pnpm build
        env:
          NODE_ENV: production
          APP_ENV: ${{ vars.APP_ENV }}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          GTM_ID: ${{ secrets.GTM_ID }}

      - name: Deploy to Cloudflare Workers
        run: pnpm run deploy:staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment PR with deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Staging Deployment Complete**\n\n' +
                    '- **URL**: https://konty-website-staging.codeusteam.workers.dev\n' +
                    '- **Commit**: ${{ github.sha }}\n' +
                    '- **Time**: ' + new Date().toISOString()
            })
